apiVersion: v1
kind: Pod
metadata:
  name: simple-app
  labels:
    svc: simple-app
spec:
  containers:
    - name: backend
      image: cptscience/nodebeaker:v9-amd64
      command: ["/usr/bin/supervisord", "-n"]
      env:
        - name: PYTHONPATH
          value: "/var/run/nodeBeaker/"
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP
  restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: simple-app
spec:
  ports:
  - name: web
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    svc : simple-app

